app/Tivix/urls.py
from django.contrib import admin
from django.urls import path, include

from Tivix.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('budgets/', include('budgets.urls')),
    path('auth/', include('users.urls')),
    path('admin/', admin.site.urls),
]

app/budgets/urls.py
from budgets.views import (
    BudgetCreateView,
    BudgetDeleteView,
    BudgetListCreateView,
    BudgetListDeleteView,
    BudgetListUpdateView,
    BudgetUpdateView,
)
from django.urls import path

app_name = "budgets"

urlpatterns = [
    path("list/create", BudgetListCreateView.as_view(), name="create_list"),
    path("list/update/<str:pk>", BudgetListUpdateView.as_view(), name="update_list"),
    path("list/delete/<str:pk>", BudgetListDeleteView.as_view(), name="delete_list"),
    path(
        "budget/create/<str:list_id>", BudgetCreateView.as_view(), name="create_budget"
    ),
    path("budget/update/<str:pk>", BudgetUpdateView.as_view(), name="update_budget"),
    path("budget/delete/<str:pk>", BudgetDeleteView.as_view(), name="delete_budget"),
]

app/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.views import LoginClassView, RegisterClassView

app_name = "users"

urlpatterns = [
    path('login/', LoginClassView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterClassView.as_view(), name='register'),
]

app/templates/partials/budget_lists.html
{% include "partials/messages.html" %}
<!-- Button trigger modal -->
<button hx-get="{% url 'budgets:create_list' %}" hx-target="#modal-content" type="submit" class="btn btn-primary mt-2"
        data-bs-toggle="modal" data-bs-target="#exampleModal">
  Add new budget list
</button>
<div class="row mt-3">
  <div class="col-sm-6 mb-2">
    <h3 class="text-center">My budget lists</h3>
    {% for list in my_lists %}
    <div class="bg-light border p-2 rounded mb-2">
      <h5 class="text-center">{{ list }}</h5>
      <button hx-get="{% url 'budgets:update_list' list.pk %}" hx-target="#modal-content" type="submit"
              class="btn btn-primary my-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Update
      </button>
      <button hx-get="{% url 'budgets:delete_list' list.pk %}" hx-target="#modal-content" type="submit"
              class="btn btn-danger my-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Delete
      </button>
      {% if list.shared_users.all %}
      <p class="fw-bold">This list is shared with:
        {% for user in list.shared_users.all %}
        {{ user }}
        {% endfor %}
      </p>
      {% endif %}
      <table class="table table-primary">
        <tr>
          <td class="table-primary">Name</td>
          <td class="table-primary">Income/Expense</td>
          <td class="table-primary">Amount</td>
          <td class="table-primary">Actions</td>
        </tr>
        {% for budget in list.budgets.all %}
        <tr class="table-{% if budget.kind == 'in' %}success{% else %}danger{% endif %}">
          <td>{{ budget.name }}</td>
          <td>{{ budget.kind }}</td>
          <td>{{ budget.amount }}</td>
          <td>
            <button hx-get="{% url 'budgets:update_budget' budget.pk %}" hx-target="#modal-content" type="submit"
                    class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">
              ✏
            </button>
            <button hx-get="{% url 'budgets:delete_budget' budget.pk %}" hx-target="#modal-content" type="submit"
                    class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">
              🗑️
            </button>
          </td>
        </tr>
        {% endfor %}
        <tr class="table-primary">
          <td>TOTAL</td>
          <td></td>
          <td>{{ list.total_amount }}</td>
          <td></td>
        </tr>
      </table>
      <button hx-get="{% url 'budgets:create_budget' list.pk %}" hx-target="#modal-content" type="submit"
              class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
        +
      </button>
    </div>
    {% endfor %}
  </div>
  <div class="col-sm-6 mb-2">
    <h3 class="text-center">Lists shared with me</h3>
    {% for list in shared_lists %}
    <div class="bg-light border p-2 rounded mb-2">
      <h5 class="text-center">{{ list }}</h5>
      <p>Author: {{ list.author }}</p>
      {% if list.shared_users.all %}
      <p class="fw-bold">This list is shared with:
        {% for user in list.shared_users.all %}
        {{ user }}
        {% endfor %}
      </p>
      {% endif %}
      <table class="table table-primary">
        <tr>
          <td class="table-primary">Name</td>
          <td class="table-primary">Income/Expense</td>
          <td class="table-primary">Amount</td>
        </tr>
        {% for budget in list.budgets.all %}
        <tr class="table-{% if budget.kind == 'in' %}success{% else %}danger{% endif %}">
          <td>{{ budget.name }}</td>
          <td>{{ budget.kind }}</td>
          <td>{{ budget.amount }}</td>
        </tr>
        {% endfor %}
        <tr class="table-primary">
          <td>TOTAL</td>
          <td></td>
          <td>{{ list.total_amount }}</td>
        </tr>
      </table>
    </div>
    {% endfor %}
  </div>
</div>

app/templates/partials/form.html
{% load crispy_forms_tags %}
<div class="text-center">
  <h3>{{ title }}</h3>
  <form class="m-auto {{ classes }}" method="{{ method }}" action="{{ url }}">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary mt-2" type="submit" value="{{ value_button }}">
  </form>
</div>

app/templates/partials/form_htmx.html
{% load crispy_forms_tags %}
<div class="text-center">
  <h5>{{ title }}</h5>
  <form class="m-auto {{ classes }}" hx-{{ method }}="{{ url }}" hx-target="#content">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary mt-2" type="submit" value="{{ value_button }}" {% if modal %}data-bs-toggle="modal" data-bs-target="#exampleModal"{% endif %}>
  </form>
</div>

app/templates/partials/messages.html
{% if messages %}
<ul class="messages mt-3">
  {% for message in messages %}
  <li {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

app/templates/partials/modal.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div id="modal-content" class="modal-content p-3">

    </div>
  </div>
</div>

app/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Tenth navbar example">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample08"
            aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {{ active_home }}" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown08" data-bs-toggle="dropdown" aria-expanded="false">{{ user }}</a>
          <ul class="dropdown-menu" aria-labelledby="dropdown08">
            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link {{ active_login }}" href="{% url 'users:login' %}">Log in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {{ active_register }}" href="{% url 'users:register' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>